In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("twitter_parsed_dataset.csv")

In [3]:
df2 = pd.read_csv("twitter_racism_parsed_dataset.csv")

In [5]:
pd.concat([df1,df2])

,index,id,Text,Annotation,oh_label
0,5.74948705591165E+017,5.74948705591165E+017,@halalflaws @biebervalue @greenlinerzjm I read...,none,0.0
1,5.71917888690393E+017,5.71917888690393E+017,@ShreyaBafna3 Now you idiots claim that people...,none,0.0
2,3.90255841338601E+017,3.90255841338601E+017,"RT @Mooseoftorment Call me sexist, but when I ...",sexism,1.0
3,5.68208850655916E+017,5.68208850655916E+017,"@g0ssipsquirrelx Wrong, ISIS follows the examp...",racism,1.0
4,5.75596338802373E+017,5.75596338802373E+017,#mkr No No No No No No,none,0.0
...,...,...,...,...,...
13466,5.75596e+17,5.75596e+17,#mkr NOOOOO!!! I wanted Kat and Andre to lose!!!,none,0.0
13467,5.58063e+17,5.58063e+17,RT @MumtazCeltik: @WhiteHouse @VP \n\n#Kobane ...,none,0.0
13468,5.75597e+17,5.75597e+17,Glad the proper competition is starting and ev...,none,0.0
13469,5.75599e+17,5.75599e+17,"No worries Pete and Manu, take all the time of...",none,0.0
13470,5.75598e+17,5.75598e+17,@mykitchenrules #mkr please kick off that lady...,none,0.0